loki:
  auth_enabled: false

deploymentMode: SingleBinary

singleBinary:
  replicas: 1

gateway:
  enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false

lokiCanary:
  enabled: false

storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin

minio:
  enabled: false

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0
