mode: deployment

image:
  repository: otel/opentelemetry-collector-k8s
  tag: "0.130.1"

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  processors:
    batch: {}

  exporters:
    otlp:
      endpoint: tempo.monitoring.svc.cluster.local:4317
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        receivers:
          -  otlp
        processors: 
          -  batch
        exporters:
          -  debug
