#testing my python app in docker
FROM python:3-slim

WORKDIR  /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir watchdog==6.0.0

ENV FLASK_ENV=development

ENTRYPOINT [ "sh", "-c", "python app.py" ]

EXPOSE 80
CMD ["gunicorn", "app:app", "-b", "0.0.0.0:80", "--log-file", "-", "--access-logfile", "-", "--workers", "4", "--keep-alive", "0"]