kind: Deployment
apiVersion: apps/v1

metadata:
  name: vote-app-deployment
  namespace: voting-app
  labels:
    app: voting-app-label

spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting-app-label
  
  template:
    metadata:
      labels:
        app: voting-app-label

    spec:
      containers:
      - name: voting-app
        image: mehulkher/voting-app:vote
        ports:
        - containerPort: 80
