kind: Deployment
apiVersion: apps/v1

metadata:
  name: db
  namespace: voting-app
  labels:
    app: postgre

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  
  template:
    metadata:
      labels:
        app: postgre

    spec:
      containers:
      - name: db
        image: postgres:9.4
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: voting-app-config
          - secretRef:
              name: voting-app-secret

---
kind: Service
apiVersion: v1

metadata:
  name: db
  namespace: voting-app

spec:
  selector:
    app: postgre
  ports:
    - port: 5432
      protocol: TCP
