FROM python:3-slim

WORKDIR  /app
# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y --no-install-recommends apache2-utils=2.4.67-1* && \
    rm -rf /var/lib/apt/lists/*

COPY . .

RUN python make-data.py

ENTRYPOINT [ "sh", "-c", "./generate-votes.sh" ]