FROM python:3-slim

WORKDIR  /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends apache2-utils2.4.66-1~deb12u1 && \
    rm -rf /var/lib/apt/lists/*

COPY . .

RUN python make-data.py

ENTRYPOINT [ "sh", "-c", "./generate-votes.sh" ]